database:
  driverClass: org.h2.Driver
  user: alexa
#  password: DevIg$2016
  password: ${DEVIGNITION_DB_PWD:-DevIg$2016}
  url: jdbc:h2:tcp://localhost/~/db/alexa
  validationQuery: "/* Alexa DB Health Check */ SELECT 42"
  properties:
    charSet: UTF-8

logging:
  level: INFO
  loggers:
    com.devignition: DEBUG
