database:
  driverClass: org.h2.Driver
  user: nest
#  password: DevIg$2016
  password: ${DEVIGNITION_DB_PWD:-DevIg$2016}
  url: jdbc:h2:tcp://localhost/~/db/nest
  validationQuery: "/* Nest DB Health Check */ SELECT 42"
  properties:
    hibernate.connection.charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.format_sql: true
    hibernate.show_sql: false

logging:
  level: INFO
  loggers:
    com.devignition: DEBUG
    org.hibernate.SQL: DEBUG
